server:
  servlet:
    context-path: /deliverySystem/api/v1

springdoc:
  swagger-ui:
    path: /public/swagger

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb+srv://dev:root@desenvolvimento.zlysth9.mongodb.net/desenvolvimento?retryWrites=true&w=majority&appName=Desenvolvimento}
      auto-index-creation: true

restaurante:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO:15}
    chave: ${JWT_CHAVE:123456}
